spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://192.168.11.217:3316/dtea?useUnicode=true&characterEncoding=UTF8&useSSL=true
    username: dtea_app
    password: GIHI7os=
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      validation-query: select 'x'
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      pool-prepared-statements: true
      max-open-prepared-statements: 20
  redis:
    database: 0
    host: 192.168.11.217
    password: nchhdtea
    timeout: 60000
    pool:
      - max-active: 8
      - max-wait: -1
      - max-idle: 8
      - min-idle: 0
server:
  port: 8769
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.hjucook.recommend.model.entity

